# Generated by Django 3.1 on 2020-08-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('R', 'Rated'), ('W', 'Wish'), ('O', 'Ongoing')], max_length=128)),
            ],
            options={
                'db_table': 'review_types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('face_image_url', models.URLField(max_length=2048, null=True)),
                ('minute_watched', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('comment', models.TextField(null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
                ('review_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.reviewtype')),
                ('user', models.ManyToManyField(to='user.User')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('film', models.ManyToManyField(to='film.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'collections',
            },
        ),
    ]
