# Generated by Django 3.1 on 2020-08-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_title', models.CharField(max_length=512)),
                ('original_title', models.CharField(max_length=256, null=True)),
                ('release_date', models.DateField()),
                ('running_time', models.TimeField()),
                ('description', models.TextField()),
                ('poster_url', models.URLField(max_length=2048, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('country', models.ManyToManyField(to='film.Country')),
            ],
            options={
                'db_table': 'films',
            },
        ),
        migrations.CreateModel(
            name='FilmURLType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('V', 'Video'), ('I', 'Image'), ('B', 'Background')], max_length=32)),
            ],
            options={
                'db_table': 'film_url_types',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('face_image_url', models.URLField(max_length=2048, null=True)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'service_providers',
            },
        ),
        migrations.CreateModel(
            name='FilmURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
                ('film_url_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.filmurltype')),
            ],
            options={
                'db_table': 'film_urls',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='film.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='service_provider',
            field=models.ManyToManyField(to='film.ServiceProvider'),
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.person')),
            ],
            options={
                'db_table': 'casts',
            },
        ),
    ]
